# Generated by Django 4.0 on 2022-01-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_holiday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='holiday',
            field=models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (7, 'Sunday')], default=7, null=True),
        ),
    ]
