# Generated by Django 4.0 on 2021-12-28 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_rename_name_contact_first_name_remove_contact_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
