# Generated by Django 4.0 on 2021-12-27 14:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_remove_appointment_time_appointment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_time',
            field=models.CharField(default=datetime.datetime(2021, 12, 27, 14, 6, 13, 14935, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
    ]
