# Generated by Django 4.0 on 2022-01-02 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('appointments', '0003_appointment_date_created_alter_appointment_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='vaccinated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vaccinated_appointments', to='auth.user'),
        ),
    ]
