# Generated by Django 4.0 on 2021-12-28 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_snippet_remove_appointment_appointment_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
